baseURL = "https://blog.simbafs.cc/"
title = "Simba's Blog"
paginate = 10
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-DTMEFY7DTF"
defaultContentLanguage = 'zh-tw'

[outputs]
	home = [ "HTML", "RSS", "JSON" ]

[minify]
	disableXML = true
	minifyOutput = true

# PaperMod config
[params]
	env = "production"
	title = "Simba 的喵窩"
	description = "雜七雜八的東西"
	keywords = [ "SimbaFs" ]
	author = "simbafs"
	images = [ "<link or path of image for opengraph, twitter-cards>" ]
	DateFormat = "2006-January-2"
	defaultTheme = "auto"
	disableThemeToggle = false
	
	ShowReadingTime = true
	ShowShareButtons = false
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = true
	disableSpecial1stPost = false
	disableScrollToTop = false
	comments = false
	hidemeta = false
	hideSummary = false
	showtoc = true
	tocopen = true

[params.assets]
	favicon = "/images/icon/icon.png"
	favicon16x16 = "/images/icon/icon-16.png"
	favicon32x32 = "/images/icon/icon-32.png"
	apple_touch_icon = "/images/icon/icon.png"
	safari_pinned_tab = "/images/icon/icon.png"

[params.label]
	text = "Home"
	icon = "/images/icon/icon.png"
	iconHeight = 35

[params.profileMode]
	enabled = true
	title = "Simba 的喵窩"
	subtitle = "雜七雜八的東西"
	imageUrl = "/images/icon/icon.png"
	imageWidth = 120
	imageHeight = 120
	imageTitle = "SimbaFs"

[[params.profileMode.buttons]]
	name = "Posts"
	url = "/archive"

[[params.profileMode.buttons]]
	name = "Categories"
	url = "/posts"

[[params.profileMode.buttons]]
	name = "About"
	url = "/about"

# [params.homeInfoParams]
#     Title = "🖐️ 哈囉！問世界安好"
#     Content = "歡迎來到我的小角落"

[[params.socialIcons]]
	name = "github"
	url = "https://github.com/simbafs"

[[params.socialIcons]]
	name = "telegram"
	url = "https://t.me/simbafs"

[[params.socialIcons]]
	name = "twitter"
	url = "https://twitter.com/simbafs"

[params.analytics.google]
	SiteVerificationTag = ""

[params.analytics.bing]
	SiteVerificationTag = ""

[params.analytics.yandex]
	SiteVerificationTag = ""

[params.cover]
	hidden = true
	hiddenInList = true
	hiddenInSingle = true

[params.editPost]
	URL = ""
	Text = ""
	appendFilePath = true

[params.fuseOpts]
	isCaseSensitive = false
	shouldSort = true
	location = 0
	distance = 1_000
	threshold = 0.4
	minMatchCharLength = 0
	keys = [ "title", "permalink", "summary", "content" ]
	
# [[menu.main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/posts/"
#     weight = 10

# [[menu.main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags/"
#     weight = 20

[[menu.main]]
	identifier = "archives"
	name = "Archives"
	url = "/archive/"
	weight = 30

[[menu.main]]
	identifier = "resource"
	name = "Resource"
	url = "/resource/"
	weight = 40

[[menu.main]]
	identifier = "search"
	name = "Search"
	url = "/search/"
	weight = 50
